### ISSUE TITLE
Не пишется комментарий

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#1]
Открыла на главной странице Вася Пупкин, выбрала у него Проекты, открыла первый попавшийся проект и нажала Оставить комментарий. Вышло окошко, но в него ничего не пишется

**Comment by soon** [comment]
Это точно окошко комментария, или просто пустой комментарий отправился? См. #6

**Comment by planfact-tester** [comment]
Архипов Андрей: В статьях комменты вообще множаться с каждым добавлением по арифметической прогрессии

**Comment by soon** [comment]
Судя по всему, только до обновления страницы. См. #3

**Comment by planfact-tester** [comment]
Да, ты прав, это я не разобралась. Нужно тогда, по-моему, чтобы слова "Оставить комментарий" были размещены над окошком для комментария, а ниже - кнопка подтверждения

**Comment by planfact-tester** [comment]
Еще нужна дата и автор комментария и лайк на коммент

**Comment by soon** [comment]
Полагаю, проблема уйдет сама по себе, когда мы добавим автора к блоку комментария + запретим оставлять пустые комменты. Посмотрим, пока оставлю тикет открытым.

**Comment by soon** [comment]
Проблема с автором и датой выделена в #11
