### ISSUE TITLE
вопрос по добавлению проектов и статей

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#12]
Зарегистрировалась как исполнитель, добавила новый проект и новую статью. После этого они отобразились на главной странице в новостях как : "Пользователь Анна добавил новую работу в портфолио" . С моей т.зр., должна быть дифференциация, что добавлено. Поскольку статья - это не проект в портфолио. По-хорошему, статьи вообще должны быть вынесены в отдельную закладку (раздел), т.к. пользователю интересно не то, что именно пишет еонкретный исполнитель, а просто полезная информация.

**Comment by Anastasia-Epanova** [comment]
Добавлена дифференциация проектов и статей
