### ISSUE TITLE
комментарии добавляются по несколько раз

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#13]
Оставила коммент к проекту, опубликовала. Написала еще один, снова опубликовала, при этом первый коммент повторился. Третий опубликовала - повторились первый (в третий раз) и второй.

**Comment by soon** [comment]
Похоже на #3. Они не пропадают после обновления страницы?

**Comment by planfact-tester** [comment]
Все верно, зашла еще раз - там все комментарии по одному разу

**Comment by soon** [comment]
Duplicate of #3
