### ISSUE TITLE
Специалисты – вынести раздел в  меню.

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#25]
Специалисты – вынести раздел в  меню.
При открытии должен быть выбор: те, на кого пользователь подписан, и все.
Если выбраны «все», то открываются категории.
У специалиста должно быть видно, когда он последний раз был на сайте, чтобы пользователь видел актуальность предложения.

**Comment by Anastasia-Epanova** [comment]
В меню которое слева?
Тогда не авторизованный пользователь не будет видеть.

**Comment by planfact-tester** [comment]
Еще нужна опция On-Line (тогда показываются те кто на портале)

**Comment by soon** [comment]
On-line вынесено в #43

**Comment by soon** [comment]
По поводу раздела "Все специалисты" - что значит "открываются категории"? Открыается страница с выбором категории, после чего уже показываются специалисты только из выбранной?

**Comment by Anastasia-Epanova** [comment]
Специалисты вынесены в левое меню, там отражаются все и те на которых подписан. On-Line отражается в профиле пользователя
