### ISSUE TITLE
расширенный поиск

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#26]
Расширенный поиск специалистов:
Территория (по умолчанию, там где зарегистрирован пользователь)
Кол-во проектов
Кол-во отзывов
Данные рейтинга по цене, качеству, скорости и дружелюбию или общий рейтинг (например не ниже 4.5)

**Comment by Anastasia-Epanova** [comment]
Fixed via 324e18159b06b1b0baaa480ead815e0dde2753f0
