### ISSUE TITLE
Аукцион (конкурс)

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#27]
Аукцион /Конкурс
Возможность оставить заявку на необходимую услугу и получить самые выгодные (подходящие) предложения.
Ремонт: в свободной форме указывается район, назначение помещения, площадь, фото помещения, необходимость выравнивания стен просто в плоскость или до прямых углов стен друг с другом (стены строго вертикальны, без отклонений), стены, пол, потолок – финишное покрытие, необходимость установки дверей, прокладывания новой проводки. Характерные особенности помещения, например, старый деревянный пол, который нужно разбирать или необходимость звукоизоляции или что-то иное.
Критерии для участия в конкурсе должны быть исходя из данных портала, например балл выше 4, кол-во оценко более 10.

**Comment by soon** [comment]
Перенесено в #38
