### ISSUE TITLE
Категории и подкатегории

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#29]
Андрей Архипов:

Друзья, давайте подумаем как лучше расширить категории. Есть понимание, что только ремонт очень узко. И есть конкуренты, хоть они и не сделаны в виде соц. сети. 

Предлагается сделать "Сферы жизни" на базе текущей таблицы категорий. А таблицу с подгатегориями сделать иерархичной. В этом случае для разной сферы жизни можно будет делать свою многоуровневую иерархию.

В качестве Сферы жизни (таблица категория) можно выделить: Дом, Образование, Рукоделие, Программирование и т.д. )) Затем для каждой сферы, своя иреархия уровней (таблица подкатегории), например, для программирования, первый уровень: Разработка сайтов, Разработка корпоративных систем, Разработка игр и т.п.. В разработке например Корпоративных систем, будет следующий уровень: Операционные системы, Аналитические, Системы поддержки принятия решений и т.д.

**Comment by Anastasia-Epanova** [comment]
Реализована иерархическая структура категорий
