### ISSUE TITLE
Комментарии не обновляются, а добавляются

### ISSUE THREAD

**Issue by soon** [soon/PlanFact-Issues#3]
До нажатия на кнопку "Оставить комментарий":

![2015-04-13-212312_1131x625_scrot](https://cloud.githubusercontent.com/assets/1177331/7119995/63104f4c-e223-11e4-87a8-d1569b151ac7.png)

После нажатия:

![2015-04-13-212338_1131x625_scrot](https://cloud.githubusercontent.com/assets/1177331/7119998/69f859ee-e223-11e4-9665-96310dc84519.png)

После обновления страницы:

![2015-04-13-212501_1131x625_scrot](https://cloud.githubusercontent.com/assets/1177331/7120024/92f2d838-e223-11e4-881b-9b619854c657.png)

**Comment by Anastasia-Epanova** [comment]
Вопрос открытый: #15. Сейчас они добавляются в конец списка.

**Comment by Anastasia-Epanova** [comment]
Fixed via 8438a0a025d82f1b6c3dd869281c747621244d32
