### ISSUE TITLE
Ошибка входа

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#30]
При авторизации после нажатии кнокпи появляется мое имя, затем окно моргает и просиходит выход. Вчера такого не было

**Comment by soon** [comment]
Странная ошибка. Убрал редирект после входа, посмотрим, поможет или нет. Не вижу изменений в кодовой базе, которые могли породить такую проблему. Тикет пока оставим открытым

Commit #f667da0243dfa499fee55b7999f1d97405fa9d34

**Comment by planfact-tester** [comment]
Не повторяется больше давайте закроем
