### ISSUE TITLE
Необходимо ли выделять проект при наведении?

### ISSUE THREAD

**Issue by soon** [soon/PlanFact-Issues#32]
В присланном дизайне при наведении на карту проекта она изменяет цвет + вокруг нее появляется тень. Это смотрится хорошо, но может несколько дизориентировать пользователя, поскольку когда применяется подобное взаимодействие, человек подсознательно считает, что вне зависимости от того, в какую область будет произведено нажатие мыши, система будет вести себя одинаково (аналогия - любая кнопка на сайте). Но на карточке есть ссылки, есть блок для добавления "лайка", поэтому предыдущее утверждение неприменимо к подобному представлению. Поэтому я не уверен, что нам стоит так делать (или, по крайней мере, делать не так агрессивно, достаточно добавить тень вокруг проекта)

**Comment by Anastasia-Epanova** [comment]
Как в дизайне:

![1](https://cloud.githubusercontent.com/assets/11835000/7214570/96b5bc24-e5ca-11e4-87ba-80f3095b77be.png)

Без подсветки, но с тенью:

![default](https://cloud.githubusercontent.com/assets/11835000/7214569/93c354cc-e5ca-11e4-9692-4d62daf67dca.png)

**Comment by planfact-tester** [comment]
А нельзя ли тень сделать более явной

**Comment by Anastasia-Epanova** [comment]
Можно. Верхняя - текущая тень, средняя - без тени, нижняя - насыщенная тень. Можно также увеличить длину тени.
![1](https://cloud.githubusercontent.com/assets/11835000/7214859/4bd1bdcc-e5d7-11e4-8940-711cc2430abd.png)

**Comment by Anastasia-Epanova** [comment]
Fixed via 601c94a7e269eae0ff47537e2158760f6e8bd878
