### ISSUE TITLE
Мои подписки - пусто

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#33]
"Мои подписки" в профиле  пустые хотя я подписался на парочку специалистов.
Давайте добавим еще там же справа ссылку "На меня подписаны". По ней можно будет видеть, кто на меня подписался. Список по алфавиту отсортировать. И чтобы можно было по щелчку на человека перейти.

**Comment by Anastasia-Epanova** [comment]
В подписках высвечиваются добавленные проекты и статьи пользователей,на которых подписан.
Мои подписчики тоже есть, если зайти с главной страницы, там где над новостью имя написано

**Comment by Anastasia-Epanova** [comment]
Специалисты, на которых подписан выводятся в левом меню, где специалисты
