### ISSUE TITLE
Сообщения

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#37]
Нужно переделать раздел "мои сообщения" по образцу во вложении.

Список контактов должен формироваться из:
1. Подписанных
2. Тех кому хоть раз отправили сообщение с профиля
![default](https://cloud.githubusercontent.com/assets/11924606/7238086/89abfca0-e7b9-11e4-8f8a-faf394f5e6a2.png)

**Comment by soon** [comment]
[Предварительные наброски разметки](https://gist.github.com/soon/adfe7237d305ebe0c08a)

**Comment by planfact-tester** [comment]
Разметка, на первый взгляд, норм

**Comment by soon** [comment]
Это чтобы потом не потерять.

**Comment by soon** [comment]
Обновлена разметка (ссылка прежняя)
