### ISSUE TITLE
Заявка

### ISSUE THREAD

**Issue by soon** [soon/PlanFact-Issues#38]
Предварительные выводы:
1. Отказываемся от User-defined fields, вместо них - описание заявки.
2. По умочанию, исполнитель подписан на категории, выбранные при регистрации.
3. У исполнителя есть возможность подписаться на выбранные категории (скорее всего, только на нижние уровни категорий).
4. Статус заявки. Пока непонятно, что это будет - Закрыта / Открыта или нужно больше состояний.

**Comment by soon** [comment]
Вопрос - ограничиваем ли мы участие? Если да, то по каким параметрам?

**Comment by planfact-tester** [comment]
Есть ли смысл ограничивать участие? Может быть только по категории специалистов, т.е. если заявка относится к конкретной категории, то и участвуют специалисты этой категории. 
А еще какие-то ограничения зачем нужны? Давайте обсудим, кто что предлагает.

**Comment by soon** [comment]
Вчера обсуждали этот вопрос. Главная проблема в том, что фильтровать необходимо по достоверным критериям. Пока на очереди "рейтинг", но если его можно легко накрутить, то он отпадает.
