### ISSUE TITLE
не добавляется проект

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#40]
Заполнила все поля при добавлении проекта, кроме категории (ее пока там нет), прикрепила фото, но проект не создался, написали " при добавлении проекта произошла ошибка"

**Comment by planfact-tester** [comment]
ранее добавленные проекты не редактируются, при попытке изменить выводится такая же ошибка

**Comment by Anastasia-Epanova** [comment]
Не добавлялось и не изменялось из-за неправильной загрузки категорий.
Переделана загрузка категорий, добавляется и изменяется нормально.
