### ISSUE TITLE
Категория специалиста

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#41]
При регистрации в качестве специалиста он должен выбрать для себя категорию, или несколько категорий (из нижнего уровня). При этом ему должны показываться все категории в виде дерева, для понимания, но квадратики для отметки выбора должны быть только у нижнего уровня.

**Comment by Anastasia-Epanova** [comment]
Fixed via 8f596d3e67bec589bc4979416591af1166072364
