### ISSUE TITLE
Вспомнить пароль

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#44]
Нужна кнопка "Вспомнить пароль", по которой на почту пользователю высылается ссылка для восстановления

**Comment by planfact-tester** [comment]
Или высылается заново сгенерированный пароль.
(Товарищи-программисты, определитесь сами, как лучше, безопаснее, кошернее...)

**Comment by soon** [comment]
Проще - новый пароль. Кошернее - ссылку для восстановления. Если стоит вопрос о том, как все сделать максимально быстро, то первый вариант предпочтительнее

**Comment by Anastasia-Epanova** [comment]
А с какого почтового ящика отправлять письмо?

**Comment by soon** [comment]
Самый простой вариант - завести бесплатную почту на gmail/yandex/etc. и отправлять оттуда
Вариант посложнее - использовать сторонние сервисы, вроде [Mailgun](http://www.mailgun.com/) или [Mandrill](https://www.mandrill.com/)  

В любом случае нас потребуется реализация отдельного модуля, который будет отправлять эти письма. Схема такая - при каком-либо действии в БД создается запись, а сам скрипт отправки писем запускается раз в N минут, проверяет наличие новых писем, если они есть - отправляет. Таким образом, даже если что-то пойдет не так:
- Мы это сможем отследить
- Для пользователя это не будет заметно (за исключением того, что не придет письмо)

**Comment by Anastasia-Epanova** [comment]
Высылается новый пароль с ящика no_replay_PlanFact@mail.ru
