### ISSUE TITLE
Кол-во публикаций у пользователя

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#48]
Давайте сделаем как в Яндекс маркет. Чтобы лишний раз не кликать, например, на ссылку отзывы, показывать сколько их там циферкой
![_](https://cloud.githubusercontent.com/assets/11924606/7275798/537ee57c-e91f-11e4-81c8-0835ca81ac02.png)

**Comment by Anastasia-Epanova** [comment]
Fixed via e7d7f18daf37783cf75eff7cdd92fe16f12c03f1
