### ISSUE TITLE
Цвета ссылок

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#50]
Местами цвета ссылок не соответствуют карте цветов. Они темно-синего цвета, дефоултного.
В не срочном порядке надо будет поправить.

Вот наша карта цветов:

https://docs.google.com/document/d/1T-FTbjMhzsIeKKiJQs03vlji-L56lqRLaZzvTxeRM4c/edit?usp=sharing

**Comment by Anastasia-Epanova** [comment]
Цвета изменены
