### ISSUE TITLE
Заявки и подача предложений

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#54]
Друзья, прошу доработать заявочную часть. Как я вижу написал во вложении

**Comment by soon** [comment]
Нет вложения. Я не уверен, что GitHub позволяет загружать что-то кроме изображений. Может на почту?

**Comment by planfact-tester** [comment]
Не могу Word прикрепить, отпадывает.
Отправил на почту

**Comment by soon** [comment]
1. Добавить возможность смотреть заявки по всем подкатегориям, выделено красным:
   ![image](https://cloud.githubusercontent.com/assets/1177331/7347691/79ffc732-ed04-11e4-9eea-30f06bfebe4c.png)
2. Сделать понятное окно подачи предложений на заявку
   ![image](https://cloud.githubusercontent.com/assets/1177331/7347686/72c5fe00-ed04-11e4-886e-97c3db677e12.png)

**Comment by planfact-tester** [comment]
Настя, Андрей говорит, что все равно надо примерные сроки указывать в формате "с - по", а потом еще одно поле для тех, кто не может указать точный период. Оказывается, это нужно для автоматического подбора и статистики.

**Comment by planfact-tester** [comment]
Вот так
![default](https://cloud.githubusercontent.com/assets/11924606/7385467/53c5bec0-ee60-11e4-897c-ca53dcf19c17.png)

**Comment by Anastasia-Epanova** [comment]
дубль #71
