### ISSUE TITLE
Название услуги

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#55]
![image](https://cloud.githubusercontent.com/assets/11924606/7368224/47e94ad2-edbf-11e4-8835-e00c90dc25b8.png)
Слова в названии услуги наезжают друг на друга, само название не видно целиком (может быть поле для ввода названия должно быть меньше?)

**Comment by Anastasia-Epanova** [comment]
![image](https://cloud.githubusercontent.com/assets/11835000/7416196/31bcc8ba-ef77-11e4-9100-3c503e02566d.png)
