### ISSUE TITLE
проблема с сообщениями

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#57]
1. на странице "мои сообщения" в двух моих аккаунтах отображается одинаковая переписка (Анна - Андрей Мастер), она по-любому не может относиться к обеим учетным записям.
2. когда я пытаюсь написать новое сообщение, после нажатия на кнопку "Отправить" вышеуказанная переписка пропадает и вместо нее появляется последнее сообщение (непонятно кому?)
3. После переключения между вкладками Мои сообщения и Отправленные последнее сообщение вообще пропадает
4. слева от сообщений показывается три картинки Васи Пупкина... все время...

**Comment by soon** [comment]
Работа над блоком сообщений еще не закончена. Есть весь функционал, кроме подгрузки списка людей, с которыми велась беседа. Поэтому там пока заглушка.

**Comment by soon** [comment]
1. Переписку убрал
2. Переписка не пропадает после нажатия кнопки "Отправить"
3. Убрана вкладка "Отправленные"
4. Добавлена подгрузка контактов

Баги предложения, связанные с сообщениями - #63, #64, #65
