### ISSUE TITLE
отображение услуги

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#58]
Добавила еще одну услугу среди своих услуг, почему-то две услуги отображаются по-разному (криво
![default](https://cloud.githubusercontent.com/assets/11924606/7375347/bbe6af76-edf9-11e4-95ee-2bf907fc647b.PNG)
)

**Comment by Anastasia-Epanova** [comment]
![image](https://cloud.githubusercontent.com/assets/11835000/7416255/88093078-ef77-11e4-8d4c-c8c51b14c3d4.png)
