### ISSUE TITLE
Не тянутся шрифты из CSS

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#7]
Шрифты отображаемые на страницы дефолтные, а не те, которые разработаны дизайнером.

**Comment by soon** [comment]
Какой браузер, какая страница?

**Comment by planfact-tester** [comment]
Mozzila FireFox, главная

**Comment by soon** [comment]
Fixed via 60fdefa0ec66086a17282a64d86514add20b7300
