### ISSUE TITLE
Профиль, штрихи

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#74]
Нужно подпись сделать по центру картинки и немного ссылки влево

![profile](https://cloud.githubusercontent.com/assets/11924606/7629699/672629ca-fa48-11e4-8016-6a0cf8e63761.png)

**Comment by Anastasia-Epanova** [comment]
Так?
![image](https://cloud.githubusercontent.com/assets/11835000/7631417/2dec5004-fa5b-11e4-8743-3ebc52e861e0.png)

**Comment by planfact-tester** [comment]
Да, так!
