### ISSUE TITLE
Добавление статьи

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#8]
1. При создании статьи он подставляет первую из всех категорий в справочнике.А должен подставлять первую из моей специализации.
2. Надо подумать, можно ли сделать текст с форматированией. Этот вопрос скорее к Андрею.

**Comment by soon** [comment]
Можно, вопрос в том, какой редактор нужен. Я обычно использую разметку Markdown ([пример](http://www.codingdrama.com/bootstrap-markdown/) библиотеки на bootstrap), но подобное оформление может быть не интуитивно для пользователя. Есть другие редакторы, но они используют html разметку, что не очень хорошо.

**Comment by planfact-tester** [comment]
Посмотрел bootstrap как то не айс. Вставил форматированный текст из Ворда, он как то не очень вставился и не интуитивно. Может все же html. Есть ссылки с примерами?

**Comment by soon** [comment]
Да, Mardown плохо себя будет вести, если в него вставить форматированный текст из ворда, потому что у них разные стили оформления текста.  
Нашел еще два более-менее красивых редактора, [Imparavi](http://imperavi.com/redactor/) и [CKEditor](http://ckeditor.com/demo). Проверил на добавление текста из ворда с простым оформлением - в целом, приемлимо, но CKEditor ведет себя лучше.

**Comment by soon** [comment]
В качестве компромисного решения могу предложить редактор на базе BB-кодов (вспомнил о них только сейчас, потому что уже давно их нигде не видел). Плюсы - сохраняет текст с использованием промежуточного языка, таким образом ликвидируется большая дыра в безопасности, как если бы мы использовали HTML-based WYSIWYG редактор. Минусы - не такой красивый, как CKEditor, меньше функций (по крайней мере, я не нашел полного аналога, поскольку многие форумы с BB кодов уходят в пользу Markdown или своих решений). Пример - [WysiBB](http://www.wysibb.com/)

**Comment by planfact-tester** [comment]
Посмотрел WysiBB, ничего так. Не понятно только как он лицензируется. На странице ничего не написано.

**Comment by soon** [comment]
[MIT](https://github.com/wbb/WysiBB#license)

**Comment by planfact-tester** [comment]
Судя по написаному - можно хоть что делать и бесплатно. Только без гарантий, ест-но.

**Comment by planfact-tester** [comment]
Сможешь прикрутить?

**Comment by soon** [comment]
Да, сейчас займусь

**Comment by soon** [comment]
Добавил пока только для статей, посмотрим, как приживется

**Comment by soon** [comment]
Вопрос о форматированном вводе вынес в #42

**Comment by Anastasia-Epanova** [comment]
Подставляется первая из моих категорий
