### ISSUE TITLE
Контакты в сообщениях

### ISSUE THREAD

**Issue by Anastasia-Epanova** [soon/PlanFact-Issues#80]
![image](https://cloud.githubusercontent.com/assets/11835000/7675902/81a6e6ba-fd57-11e4-9652-651141a476d3.png)

Лучше разбить по страницам или добавить прокрутку?

**Comment by planfact-tester** [comment]
Для контактов мне кажется лучше прокрутку и сверху поиск. Их же не должно быть много.
А можно еще область сообщений автоматически вниз продливать по высоте страницы? Когда уже не входят, появляется прокрутка. Чтобы у нас окно с контактами и сообщениями на одном уровне были
