### ISSUE TITLE
Подсветка лайка

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#81]
Можно ли сделать так, чтобы когда мышку наводишь на сердечко, показывались последние 10 человек, которые лайкнули?

**Comment by Anastasia-Epanova** [comment]
У нас незарегистрированный пользователь тоже может лайк поставить.
Чтобы показывать последних, нужно чтобы лайк только авторизованный пользователь мог поставить. А то как гостей показывать?

**Comment by planfact-tester** [comment]
Просто писать: "Гость 25.05.15 15:00"
