### ISSUE TITLE
Поправить вывод статей

### ISSUE THREAD

**Issue by Anastasia-Epanova** [soon/PlanFact-Issues#82]
![image](https://cloud.githubusercontent.com/assets/11835000/7697126/e0f340f2-fe1d-11e4-9aef-98c21679594c.png)

**Comment by soon** [comment]
Функция `convertBbToHtml` определена в файле `bbConverter.js`. Пример использования - [projectsAndArticles.js#441](https://github.com/soon/PlanFact/blob/master/web/js/projectsAndArticles.js#L441)

**Comment by Anastasia-Epanova** [comment]
Этот текст отдается в ресурсе а не в скрипте

**Comment by soon** [comment]
Ок, я вечером приду и гляну
