### ISSUE TITLE
не ставится оценка

### ISSUE THREAD

**Issue by planfact-tester** [soon/PlanFact-Issues#9]
Выбираю исполнителя, нажимаю Оценить, все ввожу, а мне выдается: Вы уже ставили оценку (хотя еще не ставила)

**Comment by Anastasia-Epanova** [comment]
Можно ли ставить оценку от анонимного пользователя?

**Comment by soon** [comment]
Fixed via 14e40158a3c23a7ad08fc5e218d5345ef76fab39
